export interface AiSkill {
  id: string;
  name: string;
  mentionKey: string; // e.g. "@slides", "@pdf-report"
  category: "Presentation" | "Document" | "Engineering" | "Design" | "Analysis" | "Testing";
  description: string;
  badge: string;
  iconName: string;
  enabled: boolean;
  systemPromptModifier: string;
  outputFormat: "slides" | "pdf" | "docx" | "svg" | "code" | "csv" | "markdown";
  examplePrompt: string;
}

export interface AiRule {
  id: string;
  title: string;
  description: string;
  category: "Coding" | "Complexity" | "Documentation" | "Design";
  ruleText: string;
  enabled: boolean;
  isBuiltIn?: boolean;
}

export const BUILT_IN_SKILLS: AiSkill[] = [
  {
    id: "slides-generator",
    name: "Presentation Deck Architect",
    mentionKey: "@slides",
    category: "Presentation",
    description: "Generate stunning, slide-by-slide presentation decks (PPT / HTML) with rich visuals, headers, and code.",
    badge: "PPT / HTML",
    iconName: "Presentation",
    enabled: true,
    systemPromptModifier: "Format your entire output as an executive presentation slide deck with sequential slides separated by '---' and slide titles using '# Slide Title'. Include bullet points, code cards, and key takeaway badges.",
    outputFormat: "slides",
    examplePrompt: "Build a 5-slide technical presentation on Graph Shortest Path algorithms with Dijkstra and A*",
  },
  {
    id: "pdf-report-generator",
    name: "Executive PDF & Whitepaper",
    mentionKey: "@pdf-report",
    category: "Document",
    description: "Produce structured, publication-ready technical whitepapers, algorithm specs, and printable PDF cheat-sheets.",
    badge: "PDF Spec",
    iconName: "FileText",
    enabled: true,
    systemPromptModifier: "Format the output as a formal technical whitepaper specification with Executive Summary, Mathematical Invariants, Step-by-Step Proof, and Complexity Bounds.",
    outputFormat: "pdf",
    examplePrompt: "Create an executive technical specification whitepaper on Dynamic Programming state compression",
  },
  {
    id: "docx-doc-generator",
    name: "Microsoft Word Tech Spec",
    mentionKey: "@docx",
    category: "Document",
    description: "Generate structured Microsoft Word .docx technical documents with headings, tables, and code snippets.",
    badge: "DOCX",
    iconName: "BookOpen",
    enabled: true,
    systemPromptModifier: "Structure your response as an enterprise Microsoft Word design document with clear section headings, input/output tables, implementation notes, and edge cases.",
    outputFormat: "docx",
    examplePrompt: "Generate a formal Microsoft Word technical design spec for a Distributed Rate Limiter",
  },
  {
    id: "flowchart-diagram-architect",
    name: "Interactive Flowchart Architect",
    mentionKey: "@flowchart",
    category: "Design",
    description: "Generate interactive Mermaid flowcharts, decision trees, sequence diagrams, and architecture state machines.",
    badge: "Flowchart / Mermaid",
    iconName: "Network",
    enabled: true,
    systemPromptModifier: "When asked for flowcharts, diagrams, or visual logic flows, generate clean, valid Mermaid syntax wrapped in ```mermaid ... ``` code blocks. Use modern directional flowcharts (`graph TD` or `flowchart LR`), sequence diagrams, or state diagrams with clear node labels, conditions, and color-coded pathways.",
    outputFormat: "markdown",
    examplePrompt: "Create an interactive flowchart diagram explaining the Binary Search algorithm decision loop",
  },
  {
    id: "canvas-flowchart-design",
    name: "Canvas & Flowchart Designer",
    mentionKey: "@canvas-design",
    category: "Design",
    description: "Create visual SVG flowcharts, memory layouts, pointer traces, and state machine diagrams.",
    badge: "SVG / Canvas",
    iconName: "Layers",
    enabled: true,
    systemPromptModifier: "Generate complete, valid SVG visual diagrams or Mermaid flowchart code illustrating state transitions, memory pointer movements, and architecture nodes.",
    outputFormat: "svg",
    examplePrompt: "Draw an SVG flowchart showing the two-pointer step-by-step state in Trapping Rainwater",
  },
  {
    id: "testcase-fuzzer",
    name: "Adversarial Test Fuzzer",
    mentionKey: "@testcase-generator",
    category: "Testing",
    description: "Generate comprehensive edge case matrices, integer overflow bounds, empty roots, and stress benchmarks.",
    badge: "Fuzzing",
    iconName: "TestTube2",
    enabled: true,
    systemPromptModifier: "Synthesize an exhaustive adversarial test suite: include empty cases, single elements, negative values, duplicates, max constraints, and cycle loops.",
    outputFormat: "code",
    examplePrompt: "Generate 15 adversarial edge cases for an in-place array rotation algorithm",
  },
  {
    id: "complexity-analyzer",
    name: "Big-O & Formal Proofs",
    mentionKey: "@complexity-analyzer",
    category: "Analysis",
    description: "Derive formal recurrence relations, Master Theorem proofs, and amortized time/space complexity bounds.",
    badge: "Formal Proof",
    iconName: "Rocket",
    enabled: true,
    systemPromptModifier: "Provide formal mathematical asymptotic analysis with recurrence relations, Master Theorem step-by-step breakdown, and tight Big-O / Omega / Theta bounds.",
    outputFormat: "markdown",
    examplePrompt: "Derive the formal mathematical proof and Big-O recurrence for Fast Fourier Transform multiplication",
  },
  {
    id: "system-designer",
    name: "Distributed System Architect",
    mentionKey: "@system-design",
    category: "Engineering",
    description: "Design high-scale distributed systems, LRU caching tiers, microservices, and database partitioning.",
    badge: "Architecture",
    iconName: "Server",
    enabled: true,
    systemPromptModifier: "Provide complete system design architecture: Functional/Non-functional requirements, API schemas, High-level diagram, Data models, Bottleneck mitigations, and Scalability calculations.",
    outputFormat: "markdown",
    examplePrompt: "Design an in-memory distributed cache with O(1) reads, TTL eviction, and thread-safe lock striping",
  },
  {
    id: "spreadsheet-matrix",
    name: "CSV & Test Matrix Generator",
    mentionKey: "@spreadsheet",
    category: "Document",
    description: "Generate CSV spreadsheets, benchmark comparison tables, and dataset fixtures for coding challenges.",
    badge: "CSV / Excel",
    iconName: "FileSpreadsheet",
    enabled: true,
    systemPromptModifier: "Format output as structured CSV data tables and markdown comparison matrices with columns for TestCaseID, Input, ExpectedOutput, TimeTaken, MemoryAllocated, Category.",
    outputFormat: "csv",
    examplePrompt: "Generate a CSV benchmark table comparing Bubble Sort, Quick Sort, and Merge Sort on 10 test sizes",
  },
  {
    id: "create-skill-builder",
    name: "AI Skill Creator & Architect",
    mentionKey: "@create-skill",
    category: "Engineering",
    description: "Architect and generate full configuration for new AI Skills with custom prompt modifiers and output schemas.",
    badge: "Meta Skill",
    iconName: "Wand2",
    enabled: true,
    systemPromptModifier: "Act as an AI Meta-Architect. Help the user construct a new AI Skill specification: Name, @mention shortcut, Target category, Detailed System Prompt Modifier, Output formatting constraints, and Sample Test Prompts.",
    outputFormat: "markdown",
    examplePrompt: "@create-skill for generating SQL indexing and schema migration strategies",
  },
  {
    id: "search-skills-catalog",
    name: "Skills Explorer & Recommendation",
    mentionKey: "@search-skills",
    category: "Analysis",
    description: "Search, discover, and recommend the best skills and prompt modifiers for any algorithm or engineering challenge.",
    badge: "Discovery",
    iconName: "Search",
    enabled: true,
    systemPromptModifier: "Analyze the user's coding problem or requirement and recommend the most effective AI skills, flags, and system modifiers to solve it with maximum quality.",
    outputFormat: "markdown",
    examplePrompt: "@search-skills for building high-concurrency websocket backends",
  },
  {
    id: "code-review-audit",
    name: "Security & Code Quality Audit",
    mentionKey: "@code-review-audit",
    category: "Engineering",
    description: "Scan code for off-by-one errors, memory leaks, concurrency races, security holes, and anti-patterns.",
    badge: "Audit & Security",
    iconName: "ShieldCheck",
    enabled: true,
    systemPromptModifier: "Perform an exhaustive static code audit: identify race conditions, off-by-one bounds, memory leaks, unhandled exceptions, and time complexity traps.",
    outputFormat: "markdown",
    examplePrompt: "@code-review-audit on the provided binary search and two-pointer implementation",
  },
  {
    id: "refactor-clean",
    name: "Clean Code & SOLID Refactor",
    mentionKey: "@refactor-clean",
    category: "Engineering",
    description: "Refactor code into production-grade, modular, idiomatic patterns with clean separation of concerns.",
    badge: "Refactoring",
    iconName: "Code2",
    enabled: true,
    systemPromptModifier: "Refactor the provided code according to clean code principles: eliminate duplicate logic, improve variable naming, extract reusable helpers, and enforce modular typing.",
    outputFormat: "code",
    examplePrompt: "@refactor-clean this Monotonic Stack implementation into modular Python 3 classes",
  },
  {
    id: "git-commit-pr",
    name: "Git Commit & PR Generator",
    mentionKey: "@git-commit-pr",
    category: "Document",
    description: "Generate Conventional Commits, PR descriptions with test plans, and release notes.",
    badge: "Git & PR",
    iconName: "Terminal",
    enabled: true,
    systemPromptModifier: "Generate Conventional Commits format (feat/fix/refactor/perf) with atomic breakdown, detailed Pull Request description, Summary of Changes, and Test Verification Matrix.",
    outputFormat: "markdown",
    examplePrompt: "@git-commit-pr for the LRU Cache implementation with O(1) eviction",
  },
  {
    id: "interactive-quiz",
    name: "Algorithm Quiz & Interview Drill",
    mentionKey: "@interactive-quiz",
    category: "Testing",
    description: "Create interactive multiple-choice questions, edge-case drills, and mock technical interview questions.",
    badge: "Interview Drill",
    iconName: "Sparkles",
    enabled: true,
    systemPromptModifier: "Construct 4 interactive interview quiz questions: Multiple Choice Question with subtle traps, Detailed Explanations for correct/incorrect answers, and invariant tests.",
    outputFormat: "markdown",
    examplePrompt: "@interactive-quiz on Dijkstra vs Bellman-Ford algorithm trade-offs",
  },
  {
    id: "formal-math-latex",
    name: "KaTeX Math Proof & Invariants",
    mentionKey: "@math-latex",
    category: "Analysis",
    description: "Derive rigorous mathematical proofs, loop invariants, and asymptotic recurrences formatted with KaTeX LaTeX.",
    badge: "LaTeX Math",
    iconName: "Rocket",
    enabled: true,
    systemPromptModifier: "Format all mathematical formulas using KaTeX LaTeX ($...$ inline and $$...$$ display). Derive formal inductive steps, loop invariants, and Master Theorem cases.",
    outputFormat: "markdown",
    examplePrompt: "@math-latex prove the optimality of Huffman coding and derive recurrence equations",
  },
];

export const DEFAULT_AI_RULES: AiRule[] = [
  {
    id: "strict-typing",
    title: "Enforce Strict Typing & Annotations",
    description: "Always include explicit type hints for parameters and return types across Python, TypeScript, and Java.",
    category: "Coding",
    ruleText: "All generated code must contain strict type annotations (e.g. Python type hints `def solve(nums: List[int]) -> int:`, TypeScript strict interfaces).",
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: "optimal-space",
    title: "Prioritize In-Place & O(1) Space",
    description: "Target minimal auxiliary memory allocations and prioritize in-place pointer manipulation where feasible.",
    category: "Complexity",
    ruleText: "Whenever possible, prefer in-place state manipulation or rolling variables to minimize auxiliary memory to O(1).",
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: "docstrings-and-invariants",
    title: "Explain Algorithmic Invariants in Docstrings",
    description: "Include a concise 2-3 line docstring at the top of functions stating the mathematical invariant.",
    category: "Documentation",
    ruleText: "Include a clean docstring for every solution stating: Core Intuition, Mathematical Invariant, Time Complexity, and Space Complexity.",
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: "clean-identifiers",
    title: "Descriptive & Production Variable Names",
    description: "Avoid cryptic single-letter variables except for standard loop indices `i, j, k`.",
    category: "Coding",
    ruleText: "Use descriptive variable names (e.g. `left_pointer`, `prefix_sum`, `visited_nodes`) instead of ambiguous abbreviations.",
    enabled: true,
    isBuiltIn: true,
  },
];
