"use client";

import React, { useEffect, useRef, useState, useId } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Maximize2,
  Copy,
  Check,
  Download,
  Code2,
  Eye,
  ZoomIn,
  ZoomOut,
  Network,
  AlertCircle,
  X,
  Scan,
  RotateCcw,
} from "lucide-react";
import { toast } from "sonner";
import { useTheme } from "next-themes";

export interface MermaidFlowchartViewerProps {
  chart: string;
  title?: string;
  isGenerating?: boolean;
  className?: string;
}

const FLOWCHART_GENERATION_STEPS = [
  { label: "Parsing structural logic & decision nodes", percent: 25 },
  { label: "Computing topological node hierarchy", percent: 55 },
  { label: "Routing vector connectors & edge labels", percent: 85 },
  { label: "Finalizing diagram layout", percent: 100 },
];

/**
 * Robust sanitizer for Mermaid code generated by LLMs.
 * Auto-quotes unquoted node labels with special characters like (, ), [, ], /, +, -, =, *, <, >, math formulas.
 */
function sanitizeMermaidChart(rawChart: string): string {
  if (!rawChart) return "";

  // 1. Strip markdown fences and unneeded wrappers
  let cleaned = rawChart
    .replace(/^```(?:mermaid)?\s*/i, "")
    .replace(/```\s*$/i, "")
    .trim();

  // 2. Ensure diagram header exists
  const firstLine = cleaned.split("\n")[0].trim().toLowerCase();
  const validHeaders = ["flowchart", "graph", "sequencediagram", "classdiagram", "statediagram", "erdiagram", "gantt", "pie", "mindmap", "timeline"];
  const hasValidHeader = validHeaders.some((h) => firstLine.startsWith(h));

  if (!hasValidHeader) {
    cleaned = `flowchart TD\n${cleaned}`;
  }

  // 3. Process lines to quote unquoted node labels and clean nested quotes
  const lines = cleaned.split("\n");
  const processedLines: string[] = [];

  for (let line of lines) {
    let l = line.trimEnd();

    // Skip comment lines or structural directives
    if (
      l.trim().startsWith("%%") ||
      l.trim().startsWith("subgraph") ||
      l.trim().startsWith("end") ||
      l.trim().startsWith("classDef") ||
      l.trim().startsWith("style")
    ) {
      processedLines.push(l);
      continue;
    }

    // Strip unparsed LaTeX $...$ from node definitions
    l = l.replace(/\$([^$\n]+)\$/g, "$1");

    // Replace literal \n with space
    l = l.replace(/\\n/g, " ");

    // Sanitize Diamond Nodes: id{...} or id{"..."}
    l = l.replace(/([a-zA-Z0-9_\-]+)\{([\s\S]*?)\}/g, (match, nodeId, inner) => {
      let content = inner.trim();
      if (content.startsWith('"') && content.endsWith('"') && content.length >= 2) {
        content = content.slice(1, -1);
      }
      content = content.replace(/"/g, "'");
      content = content.replace(/\[/g, "(").replace(/\]/g, ")");
      content = content.replace(/</g, "&lt;").replace(/>/g, "&gt;");
      return `${nodeId}{"${content}"}`;
    });

    // Sanitize Stadium Nodes: id([...]) or id(["..."])
    l = l.replace(/([a-zA-Z0-9_\-]+)\(\[([\s\S]*?)\]\)/g, (match, nodeId, inner) => {
      let content = inner.trim();
      if (content.startsWith('"') && content.endsWith('"') && content.length >= 2) {
        content = content.slice(1, -1);
      }
      content = content.replace(/"/g, "'");
      content = content.replace(/\[/g, "(").replace(/\]/g, ")");
      content = content.replace(/</g, "&lt;").replace(/>/g, "&gt;");
      return `${nodeId}(["${content}"])`;
    });

    // Sanitize Circle Nodes: id((...)) or id(("..."))
    l = l.replace(/([a-zA-Z0-9_\-]+)\(\(([\s\S]*?)\)\)/g, (match, nodeId, inner) => {
      let content = inner.trim();
      if (content.startsWith('"') && content.endsWith('"') && content.length >= 2) {
        content = content.slice(1, -1);
      }
      content = content.replace(/"/g, "'");
      content = content.replace(/\[/g, "(").replace(/\]/g, ")");
      content = content.replace(/</g, "&lt;").replace(/>/g, "&gt;");
      return `${nodeId}(("${content}"))`;
    });

    // Sanitize Box Nodes: id[...] or id["..."]
    l = l.replace(/([a-zA-Z0-9_\-]+)\[([\s\S]*?)\]/g, (match, nodeId, inner) => {
      let content = inner.trim();
      if (content.startsWith('"') && content.endsWith('"') && content.length >= 2) {
        content = content.slice(1, -1);
      }
      content = content.replace(/"/g, "'");
      content = content.replace(/\[/g, "(").replace(/\]/g, ")");
      content = content.replace(/</g, "&lt;").replace(/>/g, "&gt;");
      return `${nodeId}["${content}"]`;
    });

    // Sanitize Edge Labels: -- "Label" --> or -- Label --> or |"Label"| or |Label|
    l = l.replace(/--\s*"([^"]*)"\s*-->/g, (m, lbl) => `-- "${lbl.replace(/"/g, "'")}" -->`);
    l = l.replace(/\|\s*"([^"]*)"\s*\|/g, (m, lbl) => `|"${lbl.replace(/"/g, "'")}"|`);

    processedLines.push(l);
  }

  return processedLines.join("\n");
}

export default function MermaidFlowchartViewer({
  chart,
  title = "System Architecture / Logic Flowchart",
  isGenerating = false,
  className = "",
}: MermaidFlowchartViewerProps) {
  const { theme } = useTheme();
  const uniqueId = useId().replace(/[^a-zA-Z0-9]/g, "_");
  const containerRef = useRef<HTMLDivElement>(null);
  const svgWrapperRef = useRef<HTMLDivElement>(null);

  const [svgContent, setSvgContent] = useState<string>("");
  const [isRendering, setIsRendering] = useState<boolean>(true);
  const [renderError, setRenderError] = useState<string | null>(null);
  const [showRawCode, setShowRawCode] = useState<boolean>(false);
  const [isCopied, setIsCopied] = useState<boolean>(false);
  const [isLightboxOpen, setIsLightboxOpen] = useState<boolean>(false);

  // Zoom state
  const [zoomLevel, setZoomLevel] = useState<number>(1);
  const [currentStepIdx, setCurrentStepIdx] = useState<number>(0);
  const [progressPercent, setProgressPercent] = useState<number>(25);

  // Keyboard shortcut listener for Lightbox (Esc key)
  useEffect(() => {
    if (!isLightboxOpen) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        setIsLightboxOpen(false);
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isLightboxOpen]);

  useEffect(() => {
    if (!isRendering) {
      setProgressPercent(100);
      setCurrentStepIdx(FLOWCHART_GENERATION_STEPS.length - 1);
      return;
    }

    const interval = setInterval(() => {
      setCurrentStepIdx((prev) => {
        const next = prev < FLOWCHART_GENERATION_STEPS.length - 2 ? prev + 1 : prev;
        setProgressPercent(FLOWCHART_GENERATION_STEPS[next].percent);
        return next;
      });
    }, 900);

    return () => clearInterval(interval);
  }, [isRendering]);

  // Render Mermaid Diagram to SVG
  useEffect(() => {
    let isMounted = true;

    async function renderMermaidChart() {
      setIsRendering(true);
      setRenderError(null);

      try {
        const mermaidModule = await import("mermaid");
        const mermaid = mermaidModule.default;

        const isDark = theme === "dark";

        // Initialize with monochrome EasyCode dark & light theme tokens (Strictly Zero Green)
        mermaid.initialize({
          startOnLoad: false,
          suppressErrorRendering: true,
          theme: "base",
          securityLevel: "loose",
          fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace',
          themeVariables: isDark
            ? {
                darkMode: true,
                background: "#0D0D0C",
                primaryColor: "#1C1B19",
                primaryTextColor: "#EDEDEB",
                primaryBorderColor: "#383532",
                lineColor: "#8C8880",
                secondaryColor: "#18181B",
                secondaryTextColor: "#D4D0C8",
                secondaryBorderColor: "#2A2826",
                tertiaryColor: "#141414",
                tertiaryTextColor: "#D4D0C8",
                tertiaryBorderColor: "#33312E",
                mainBkg: "#1C1B19",
                nodeBorder: "#4A4742",
                clusterBkg: "rgba(255, 255, 255, 0.02)",
                clusterBorder: "rgba(255, 255, 255, 0.1)",
                titleColor: "#FFFFFF",
                edgeLabelBackground: "#18181B",
                nodeTextColor: "#EDEDEB",
              }
            : {
                darkMode: false,
                background: "#FAF8F5",
                primaryColor: "#FFFFFF",
                primaryTextColor: "#1C1B19",
                primaryBorderColor: "#DFDAD0",
                lineColor: "#7A756C",
                secondaryColor: "#F4F1EA",
                secondaryTextColor: "#1C1B19",
                secondaryBorderColor: "#DFDAD0",
                tertiaryColor: "#FAF8F5",
                tertiaryTextColor: "#1C1B19",
                tertiaryBorderColor: "#D4D0C8",
                mainBkg: "#FFFFFF",
                nodeBorder: "#C5C0B5",
                clusterBkg: "rgba(0, 0, 0, 0.02)",
                clusterBorder: "rgba(0, 0, 0, 0.08)",
                titleColor: "#1C1B19",
                edgeLabelBackground: "#FFFFFF",
                nodeTextColor: "#1C1B19",
              },
        });

        const sanitizedCode = sanitizeMermaidChart(chart);
        const renderId = `mermaid_chart_${uniqueId}_${Date.now()}`;
        
        // Validate syntax with parse first
        await mermaid.parse(sanitizedCode);
        const { svg } = await mermaid.render(renderId, sanitizedCode);

        // Normalize SVG styles so it scales responsively to the container both horizontally & vertically
        let responsiveSvg = svg
          .replace(/style="[^"]*max-width:[^;"]*;?[^"]*"/i, 'style="max-width: 100%; max-height: 480px; width: auto; height: auto; display: block; margin: 0 auto;"')
          .replace(/height="[^"]*"/i, 'height="auto"');

        if (!responsiveSvg.includes("preserveAspectRatio")) {
          responsiveSvg = responsiveSvg.replace(/<svg\b/i, '<svg preserveAspectRatio="xMidYMid meet" ');
        }

        // Calculate initial auto-zoom scale directly from viewBox so diagram is fully visible immediately
        const viewBoxMatch = responsiveSvg.match(/viewBox=["']([0-9.\s,-]+)["']/i);
        if (viewBoxMatch) {
          const parts = viewBoxMatch[1].trim().split(/[\s,]+/).map(Number);
          if (parts.length === 4 && parts[2] > 0 && parts[3] > 0) {
            const naturalW = parts[2];
            const naturalH = parts[3];
            const targetW = (containerRef.current?.clientWidth || 800) - 48;
            const targetH = 440;
            const fitScale = Math.min(targetW / naturalW, targetH / naturalH, 1);
            setZoomLevel(Math.max(0.35, Number(fitScale.toFixed(2))));
          }
        }

        if (isMounted) {
          setSvgContent(responsiveSvg);
          setIsRendering(false);
        }
      } catch (err: any) {
        // Remove any stray error SVGs that Mermaid may have appended to document body
        if (typeof document !== "undefined") {
          document.querySelectorAll('[id^="dmermaid_"], [id^="mermaid_"]').forEach((el) => {
            if (el.textContent?.includes("Syntax error in text") || el.id.startsWith("dmermaid_")) {
              el.remove();
            }
          });
        }
        if (isMounted) {
          try {
            // Attempt AI Auto-Healing
            const repairRes = await fetch("/api/code/chat-output", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                inputMessage: `Fix this broken Mermaid flowchart syntax. Mermaid parser returned error: "${err?.message || "Syntax error"}". Code:\n${chart}\nOutput ONLY the valid Mermaid diagram enclosed in \`\`\`mermaid ... \`\`\` code fence. Every node label with math or special characters MUST be enclosed in double quotes.`,
                targetModel: "gemini-2.0-flash",
                stream: false,
              }),
            });

            if (repairRes.ok) {
              const data = await repairRes.json();
              const match = data.output?.match(/```(?:mermaid)?\s*([\s\S]*?)```/i);
              const repairedCode = match ? match[1].trim() : data.output?.trim();
              if (repairedCode) {
                const mermaidModule = await import("mermaid");
                const sanitizedRepaired = sanitizeMermaidChart(repairedCode);
                const healedId = `mermaid_healed_${uniqueId}_${Date.now()}`;
                await mermaidModule.default.parse(sanitizedRepaired);
                const { svg } = await mermaidModule.default.render(healedId, sanitizedRepaired);
                if (isMounted) {
                  setSvgContent(svg);
                  setIsRendering(false);
                  setRenderError(null);
                  return;
                }
              }
            }
          } catch (aiErr) {
            console.warn("AI Auto-Repair attempt failed:", aiErr);
          } finally {
            if (typeof document !== "undefined") {
              document.querySelectorAll('[id^="dmermaid_"], [id^="mermaid_"]').forEach((el) => {
                if (el.textContent?.includes("Syntax error in text") || el.id.startsWith("dmermaid_")) {
                  el.remove();
                }
              });
            }
          }

          setRenderError(err?.message || "Failed to render flowchart syntax");
          setIsRendering(false);
        }
      }
    }

    renderMermaidChart();

    return () => {
      isMounted = false;
    };
  }, [chart, theme, uniqueId]);

  const handleCopyCode = async () => {
    try {
      await navigator.clipboard.writeText(chart);
      setIsCopied(true);
      toast.success("Mermaid diagram code copied to clipboard");
      setTimeout(() => setIsCopied(false), 2000);
    } catch (e) {
      toast.error("Failed to copy code");
    }
  };

  const handleDownloadSvg = () => {
    if (!svgContent) return;
    try {
      const blob = new Blob([svgContent], { type: "image/svg+xml;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      const cleanTitle = title.slice(0, 30).replace(/[^a-zA-Z0-9]/g, "_").toLowerCase();
      link.download = `${cleanTitle || "flowchart"}_${Date.now()}.svg`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast.success("Downloaded SVG vector flowchart");
    } catch (e) {
      toast.error("Failed to download SVG");
    }
  };

  const handleZoomIn = () => setZoomLevel((prev) => Math.min(prev + 0.2, 2.5));
  const handleZoomOut = () => setZoomLevel((prev) => Math.max(prev - 0.2, 0.35));
  const handleResetZoom = () => setZoomLevel(1);

  const handleAutoFit = () => {
    if (!containerRef.current) return;
    const svgEl = containerRef.current.querySelector("svg");
    if (!svgEl) return;
    const containerWidth = containerRef.current.clientWidth - 48;
    const containerHeight = 440;
    let svgWidth = 0;
    let svgHeight = 0;
    const viewBox = svgEl.getAttribute("viewBox");
    if (viewBox) {
      const parts = viewBox.split(/[\s,]+/).map(Number);
      if (parts.length === 4 && parts[2] > 0 && parts[3] > 0) {
        svgWidth = parts[2];
        svgHeight = parts[3];
      }
    }
    if (!svgWidth) {
      svgWidth = svgEl.clientWidth || parseFloat(svgEl.getAttribute("width") || "0");
      svgHeight = svgEl.clientHeight || parseFloat(svgEl.getAttribute("height") || "0");
    }
    if (svgWidth > 0 && containerWidth > 0) {
      const scaleX = containerWidth / svgWidth;
      const scaleY = containerHeight / (svgHeight || containerHeight);
      const fitScale = Math.min(scaleX, scaleY, 1);
      setZoomLevel(Math.max(0.35, Number(fitScale.toFixed(2))));
    }
  };

  useEffect(() => {
    if (!svgContent) return;
    const timer = setTimeout(handleAutoFit, 120);
    return () => clearTimeout(timer);
  }, [svgContent]);

  return (
    <div
      ref={containerRef}
      className={`my-3 rounded-2xl overflow-hidden border border-[#DFDAD0] dark:border-[#383532] bg-[#FAF8F5] dark:bg-[#121212] shadow-sm transition-all ${className}`}
      style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif' }}
    >
      {/* Top Header Bar (Clean Monochrome) */}
      <div className="h-9 px-3.5 bg-black/[0.02] dark:bg-white/[0.02] border-b border-[#DFDAD0] dark:border-[#383532] flex items-center justify-between text-xs">
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1.5 font-mono text-[11px] text-[#1C1B19] dark:text-[#EDEDEB] font-medium">
            <Network className="w-3.5 h-3.5 text-[#7A756C] dark:text-[#8C8880]" />
            <span>Flowchart & Diagram</span>
          </div>
          <span className="text-black/20 dark:text-white/20">|</span>
          <span className="text-[11px] text-[#7A756C] dark:text-[#8C8880] truncate max-w-[240px]">
            {title}
          </span>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-1">
          {/* Zoom Controls */}
          {!showRawCode && !isRendering && !renderError && (
            <div className="flex items-center gap-0.5 mr-1 bg-black/[0.04] dark:bg-white/[0.06] rounded-lg p-0.5 border border-black/[0.04] dark:border-white/[0.06]">
              <button
                onClick={handleZoomOut}
                className="p-1 rounded text-neutral-500 hover:text-neutral-900 dark:hover:text-white hover:bg-black/5 dark:hover:bg-white/10 transition-colors cursor-pointer"
                title="Zoom Out"
              >
                <ZoomOut className="w-3 h-3" />
              </button>
              <button
                onClick={handleResetZoom}
                className="px-1.5 py-0.5 text-[10px] font-mono text-neutral-600 dark:text-neutral-300 hover:text-neutral-900 dark:hover:text-white transition-colors cursor-pointer"
                title="Reset Zoom"
              >
                {Math.round(zoomLevel * 100)}%
              </button>
              <button
                onClick={handleZoomIn}
                className="p-1 rounded text-neutral-500 hover:text-neutral-900 dark:hover:text-white hover:bg-black/5 dark:hover:bg-white/10 transition-colors cursor-pointer"
                title="Zoom In"
              >
                <ZoomIn className="w-3 h-3" />
              </button>
              <button
                onClick={handleAutoFit}
                className="p-1 rounded text-neutral-500 hover:text-neutral-900 dark:hover:text-white hover:bg-black/5 dark:hover:bg-white/10 transition-colors cursor-pointer"
                title="Auto Fit to Screen"
              >
                <Scan className="w-3 h-3" />
              </button>
            </div>
          )}

          {/* Toggle Raw Mermaid Code */}
          <button
            onClick={() => setShowRawCode(!showRawCode)}
            className="p-1.5 rounded-lg text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white hover:bg-black/[0.04] dark:hover:bg-white/[0.06] transition-colors cursor-pointer flex items-center gap-1"
            title={showRawCode ? "Show Visual Diagram" : "View Raw Mermaid Code"}
          >
            {showRawCode ? <Eye className="w-3.5 h-3.5" /> : <Code2 className="w-3.5 h-3.5" />}
          </button>

          {/* Copy Mermaid Code */}
          <button
            onClick={handleCopyCode}
            className="p-1.5 rounded-lg text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white hover:bg-black/[0.04] dark:hover:bg-white/[0.06] transition-colors cursor-pointer"
            title="Copy Diagram Code"
          >
            {isCopied ? <Check className="w-3.5 h-3.5 text-neutral-900 dark:text-white" /> : <Copy className="w-3.5 h-3.5" />}
          </button>

          {/* Download Vector SVG */}
          <button
            onClick={handleDownloadSvg}
            disabled={!svgContent || isRendering}
            className="p-1.5 rounded-lg text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white hover:bg-black/[0.04] dark:hover:bg-white/[0.06] transition-colors cursor-pointer disabled:opacity-40"
            title="Export as Vector SVG"
          >
            <Download className="w-3.5 h-3.5" />
          </button>

          {/* Fullscreen Lightbox */}
          <button
            onClick={() => setIsLightboxOpen(true)}
            className="p-1.5 rounded-lg text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white hover:bg-black/[0.04] dark:hover:bg-white/[0.06] transition-colors cursor-pointer"
            title="Expand Fullscreen"
          >
            <Maximize2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Main Flowchart Canvas Container */}
      <div className="relative w-full min-h-[240px] max-h-[560px] overflow-auto p-4 flex items-center justify-center select-none bg-black/[0.01] dark:bg-white/[0.01]">
        {/* Shimmer state while generating / rendering */}
        {isRendering && !renderError && (
          <div className="relative z-10 flex flex-col items-center justify-center text-center p-6 space-y-3 max-w-[85%]">
            <div className="p-3 rounded-2xl bg-black/[0.04] dark:bg-white/[0.06] border border-black/[0.06] dark:border-white/[0.08] text-neutral-600 dark:text-neutral-300">
              <Network className="w-5 h-5 animate-pulse" />
            </div>

            <div className="space-y-1">
              <p className="shimmer text-xs font-mono tracking-wide uppercase font-medium">
                {FLOWCHART_GENERATION_STEPS[currentStepIdx]?.label || "Synthesizing diagram layout..."}
              </p>
            </div>

            {/* Mini Progress Bar (Monochrome) */}
            <div className="w-36 h-1 rounded-full bg-black/10 dark:bg-white/10 overflow-hidden">
              <motion.div
                initial={{ width: "15%" }}
                animate={{ width: `${progressPercent}%` }}
                transition={{ duration: 0.8 }}
                className="h-full bg-neutral-800 dark:bg-neutral-200 rounded-full"
              />
            </div>
          </div>
        )}

        {/* Visual Rendered SVG Diagram */}
        {!showRawCode && !isRendering && !renderError && svgContent && (
          <motion.div
            initial={{ opacity: 0, scale: 0.98 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            ref={svgWrapperRef}
            style={{
              transform: `scale(${zoomLevel})`,
              transformOrigin: "center center",
              transition: "transform 0.15s ease-out",
            }}
            className="w-full flex items-center justify-center p-2 [&>svg]:max-w-full [&>svg]:max-h-[480px] [&>svg]:w-auto [&>svg]:h-auto [&>svg]:overflow-visible"
            dangerouslySetInnerHTML={{ __html: svgContent }}
          />
        )}

        {/* Raw Mermaid Code View */}
        {showRawCode && (
          <div className="w-full max-h-[420px] overflow-auto rounded-xl bg-[#141414] text-neutral-100 p-4 text-xs font-mono select-text leading-relaxed border border-white/10">
            <pre>
              <code>{chart}</code>
            </pre>
          </div>
        )}

        {/* Error Fallback */}
        {renderError && (
          <div className="relative z-10 flex flex-col items-center justify-center p-6 text-center space-y-2 text-neutral-600 dark:text-neutral-400 text-xs">
            <AlertCircle className="w-5 h-5 text-neutral-500" />
            <p className="font-semibold text-neutral-900 dark:text-neutral-100">Unable to parse diagram structure</p>
            <p className="text-neutral-500 max-w-[340px] text-[11px] font-mono">{renderError}</p>
            <button
              onClick={() => setShowRawCode(true)}
              className="text-xs bg-black/[0.05] dark:bg-white/[0.08] text-neutral-800 dark:text-neutral-200 px-3 py-1 rounded-lg hover:bg-black/[0.1] dark:hover:bg-white/[0.15] transition-colors cursor-pointer border border-black/[0.06] dark:border-white/[0.08]"
            >
              View Diagram Code
            </button>
          </div>
        )}
      </div>

      {/* Fullscreen Lightbox Modal (Click anywhere or press Esc to close) */}
      <AnimatePresence>
        {isLightboxOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-black/95 backdrop-blur-md flex flex-col items-center justify-between p-4 select-none cursor-pointer"
            onClick={() => setIsLightboxOpen(false)}
          >
            {/* Modal Header */}
            <div
              className="w-full flex items-center justify-between text-neutral-300 text-xs py-2 px-4 cursor-default"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center gap-2">
                <span className="font-mono text-white font-medium uppercase">Flowchart Canvas</span>
                <span className="text-neutral-500">|</span>
                <span className="truncate max-w-[400px] text-neutral-300">{title}</span>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleDownloadSvg}
                  className="px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white font-medium flex items-center gap-1.5 cursor-pointer text-xs transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download SVG</span>
                </button>
                <button
                  onClick={() => setIsLightboxOpen(false)}
                  className="p-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white cursor-pointer transition-colors"
                  title="Close (Esc)"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Modal Center Content */}
            <div
              className="flex-1 w-full max-h-[85vh] flex items-center justify-center p-4 overflow-auto [&>svg]:max-w-full [&>svg]:max-h-full"
              dangerouslySetInnerHTML={{ __html: svgContent }}
            />

            {/* Modal Footer */}
            <div className="text-neutral-500 text-[11px] font-mono py-2">
              Click anywhere outside or press Esc to close
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
